[package]
name = "wasabi"
version = "0.2.0"
authors = ["Daniel Lehmann <daniel.lehmann@crisp-da.de>"]
edition = "2018"

[dependencies]
wasm = { path = "lib/wasm" }
test_utilities = { path = "lib/test_utilities" }
rayon = "1.0"
parking_lot = "0.6.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_plain = "0.3.0"

# [profile.release]
# debug = true
